### ISSUE TITLE
missing 0001_initals.py for all app models

### ISSUE THREAD

**Issue by ZhisongZhang** [Landgate/Medjil#16]
hi guys, 

I have tried to pull the main branch and installed all the required packages. however, I come across problems when doing the python manage.py migrate. seems like all 0001_initial.py files are missing which causes the makemigrations and migrate failed

**Comment by ZhisongZhang** [comment]
> hi guys,
> 
> I have tried to pull the main branch and installed all the required packages. however, I come across problems when doing the python manage.py migrate. seems like all 0001_initial.py files are missing which causes the makemigrations and migrate failed

I have managed to fix all problems using the patch branch. It will be better for you guys to fix to the main branch. I have also dockerised the project on my end so that other team members here can easily test the project without worrying about installing all dependencies.

**Comment by KentWheeler** [comment]
Thanks for the fix and comments. Sorry for the delay replying, we have been on leave for a bit and only just saw your message. 
I believe the 0001_initial.py files should be automatically created when you first run the makemigrations command. However, in acknowledgement of your the challenge you had getting a working version up and running I think I will change the repository so that it has a sample database ready to go.

**Comment by ZhisongZhang** [comment]
I have a dockerised version of the repo, would you mind I share it with you guys? We will be testing the code this year at DELWP and I am happy to become a contributor if you like.

**Comment by ZhisongZhang** [comment]
Hi Kent,

I will repackage your updated repo and share it with you.

Regards,
Zhisong
